defmodule FlowerField do
  @doc """
  Annotate empty spots next to flowers with the number of flowers next to them.
  """

  # This solution lets flowers of 3*3-matrices (with all ones, but -1 in the center)
  # 'bloom' from every flower position in the garden. These matrix flowers can then
  # be added up (keeping -1 at the positions of the original flowers)
  # to generate the right numbers just at the positions where
  # they belong by summing them columnwise amd rowwise
  # That means that a single row of the input garden gives rise to a
  # 3*columns 'row_flower' of columnwise added up matrix flowers
  # The tricky part is to add the row_flowers generated by different rows.
  # This is done in the accumulator of Enum.reduce in the annotate-function
  # In the end, we have to truncate the summed up 'matrix' of neighbour counts
  # (on all four sides there is one row or column too much) and
  # lastly turn the numbers to the right characters for output.

  # Let the matrix flowers bloom !!!

  @spec annotate([String.t()]) :: [String.t()]
  def annotate([]), do: []
  def annotate([""]), do: [""]
  def annotate(board) do
    cols = board |> Enum.at(0) |> String.length()
    board
    # generate all row_flowers (already added the flowers columnwise) and then add these up row by row
    |> Enum.map(&get_flowers(&1, cols))
    |> Enum.reduce(fn row_flower, acc ->
      # the last two lines of the accumulator will be changed by adding the next row_flower, so drop them
      # and then calculate the new two lines by taking the sum of the right rows of acc and row_flower
      (acc |> Enum.drop(-2)) ++ [
        add_arrs(acc |> Enum.at(-2), row_flower |> Enum.at(-3)),
        add_arrs(acc |> Enum.at(-1), row_flower |> Enum.at(-2)),
        row_flower |> Enum.at(-1)
      ]
    end)
    |> then(&clean_up/1)
  end

  defp get_flowers(row, cols) do
    default_list = List.duplicate(List.duplicate(0, cols + 2), 3)
    row
    |> String.codepoints
    |> Enum.with_index
    |> Enum.filter(&(elem(&1, 0) == "*"))
    |> Enum.map(fn {_, col} -> flower(col, cols) end)
    |> Enum.reduce(default_list, &add_flowers/2)
  end

  # we generate every 3*3 matrix flower already as part of an otherwise empty row_flower
  defp flower(col, cols) do
    edge = [1, 1, 1] ++ List.duplicate(0, cols - 1)
    middle = [1, -1, 1] ++ List.duplicate(0, cols - 1)
    # put the matrix flower at the beginning of the row_flower
    if col == 0 do
      [edge, middle, edge]
    # or slide it to the column where it belongs
    else
      edge = Enum.slide(edge, 0..2, col + 2)
      middle = Enum.slide(middle, 0..2, col + 2)
      [edge, middle, edge]
    end
  end

  defp add_flowers(flower1, flower2) do
    Enum.zip(flower1, flower2) |> Enum.map(fn {arr1, arr2} -> add_arrs(arr1, arr2) end)
  end

  defp add_arrs(arr1, arr2) do
    Enum.zip(arr1, arr2) |> Enum.map(fn {el1, el2} -> add_nums(el1, el2) end)
  end

  # keep the -1 at the original flower positions
  defp add_nums(el1, el2) when el1 < 0 or el2 < 0, do: -1
  defp add_nums(el1, el2), do: el1 + el2

  defp clean_up(result_rows) do
    result_rows |> Enum.drop(1) |> Enum.drop(-1) |> Enum.map(&get_result_string/1)
  end

  defp get_result_string(row) do
    row |> Enum.drop(1)|> Enum.drop(-1)
    |> Enum.map(fn num ->
      case num do
        -1 -> "*"
        0  -> " "
        n  -> Integer.to_string(n)
      end
    end)
    |> Enum.join
  end
end
